### ISSUE TITLE
About the RadarScene dataset.

### ISSUE THREAD

**Issue by Yinbao-Li** [Xiangyu-Gao/deformable_radar_polygon_occupancy_representation#2]
So there is no z coordinate for each point within the data set, right? or you just didn't use it?

**Comment by Xiangyu-Gao** [comment]
According to the description of the dataset, https://radar-scenes.com/dataset/structure/, the z coordinates was not provided.

**Comment by Yinbao-Li** [comment]
Got it, thanks for reply.
